/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../predictive_maintenance.json.  Do not edit it directly.

#pragma once
#include "avnet_mt3620_sk.h"

// Button A
#define BUTTON_A AVNET_MT3620_SK_USER_BUTTON_A

// Button B
#define BUTTON_B AVNET_MT3620_SK_USER_BUTTON_B

// LED 2
#define APP_STATUS_LED AVNET_MT3620_SK_APP_STATUS_LED_YELLOW

// AVNET: Network Connected
#define NETWORK_CONNECTED_LED AVNET_MT3620_SK_WLAN_STATUS_LED_YELLOW

// AVNET Start Kit Definition
#define ISU2_I2C AVNET_MT3620_SK_ISU2_I2C

// AVNET Start Kit Definition
#define Adc0 AVNET_MT3620_SK_ADC_CONTROLLER0

// EN
#define EN AVNET_MT3620_SK_GPIO16

// NSL
#define NSL AVNET_MT3620_SK_GPIO34

// PH
#define PH AVNET_MT3620_SK_GPIO0

// RELAY_2
#define RELAY_2 AVNET_MT3620_SK_GPIO35

// RELAY_EXT
#define RELAY_EXT AVNET_MT3620_SK_GPIO1

// PWM CONTROLLER 2: channel 0 is used by User LED Red, channel 1 is used by User LED Green, channel 2 is used by User LED Blue. Pins for this controller are shared with AVNET_MT3620_SK_USER_LED_RED, AVNET_MT3620_SK_USER_LED_GREEN, and AVNET_MT3620_SK_USER_LED_BLUE. If this PWM controller is requested, none of these GPIOs can be used.
#define PWM_RGB_CONTROLLER AVNET_MT3620_SK_PWM_CONTROLLER2

